apiVersion: v1
kind: Secret
metadata:
  name: azdocreds
  labels:
    {{- include "azdochart.labels" . | nindent 4 }}
type: "opaque"
stringData:
  AZP_TOKEN:  {{ .Values.AZP_TOKEN }}
  AZP_URL:  {{ .Values.AZP_URL }}
  AZP_POOL: {{ .Values.AZP_POOL }}